@startuml
left to right direction
:Agente: as Ag
(Evaluar \n Solicitud de Crédito) as ESC
(Solicitar Información adicional al cliente) as SIA

Ag --> ESC
ESC <.. SIA : <<extend>> Si ingresos < 1000
@enduml